# Generated by Django 5.1.6 on 2025-03-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_customuser_alter_csvupload_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customuser',
        ),
    ]
